sources:
    - ammonia-delta.fontra
recipe:
    ../fonts/Ammonia-Delta-avar2.ttf:
        - source: ammonia-delta.fontra
        - operation: exec
          exe: fontra-compile
          args: $in $out
        - operation: buildAvar2
          args: $in ammonia-delta.fontra/font-data.json
    # ../fonts/Ammonia-Delta-avar1.ttf:
    #     - source: ../fonts/Ammonia-Delta-avar2.ttf
    #     - operation: exec
    #       exe: gftools avar2-to-avar1
    #       args: -o $out $in
